// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Annotation = {
  id: number;
  bookId: number;
  cfi: string;
  /**
   * The selected text at creation time.
   */
  text: string;
  note: string | null;
  /**
   * One of: yellow, green, blue, pink
   */
  color: string;
  /**
   * "highlight" or "underline"
   */
  style: string;
  createdAt: number;
};
