// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Bookmark = {
  id: number;
  bookId: number;
  cfi: string;
  /**
   * Short context label (e.g. chapter or excerpt) shown in the list.
   */
  label: string;
  createdAt: number;
};
