// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Book } from "./Book";

export type ImportResult =
  | { status: "imported"; book: Book }
  | { status: "duplicate"; path: string }
  | { status: "unsupported"; path: string }
  | { status: "failed"; path: string; message: string };
