// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NewAnnotation = {
  bookId: number;
  cfi: string;
  text: string;
  note: string | null;
  color: string;
  style: string;
};
